#ifndef USB_DEVICE_H_
#define USB_DEVICE_H_

enum {
    USB_DEVICE_REPORT_ID_KEYBOARD = 1,
    USB_DEVICE_REPORT_ID_MOUSE,
    USB_DEVICE_REPORT_ID_CONSUMER_CONTROL,
    USB_DEVICE_REPORT_ID_COUNT
};

#endif
